---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.15.3
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    worker:
      config:
        core:
          sources:
            - pci
            - usb
            - custom
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "03"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - "class"
              - "vendor"
              - "device"
          custom:
            - name: "intel-gpu"
              matchOn:
                - pciId:
                    class: ["0300"]
                    vendor: ["8086"]
            - name: "zwave"
              matchOn:
                - usbId:
                    class: ["02"]
                    vendor: ["0658"]
                    device: ["0200"]
            - name: "zigbee"
              matchOn:
                - usbId:
                    class: ["ff"]
                    vendor: ["1a86"]
                    device: ["7523"]
            - name: "intel-10g"
              matchOn:
                - pciId:
                    class: ["0200"]
                    vendor: ["8086"]
                    device: ["10fb"]
            - name: "coral-tpu"
              matchOn:
                - usbId:
                    vendor: ["1a6e", "18d1"]
            - name: "vega11-gpu"
              matchOn:
                - pciId:
                    class: ["0300"]
                    vendor: ["1002"]
                    device: ["15dd"]

    prometheus:
      enable: true
