---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: homeassistant/home-assistant
              tag: 2024.3.3@sha256:a4c2b7a75e8d5168a9e9f78d9d9f7f36435e2da07899e7faf5f6e3cdc4eebe56
            env:
            - name: TZ
              value: ${TIMEZONE}
            - name: SECRET_EXTERNAL_URL
              value: https://home.${SECRET_DOMAIN}
            - name: SECRET_TRUSTED_PROXIES_1
              value: ${CLUSTER_CIDR}
            - name: SECRET_TRUSTED_PROXIES_2
              value: ${NODE_CIDR}

            # Home-Assistant Zones
            - name: SECRET_ZONE_HOME_HOUSE_NUMBER
              value: "${SECRET_HOUSE_NUMBER}"
            - name: SECRET_ZONE_HOME_POSTAL_CODE
              value: "${SECRET_POSTAL_CODE}"
            - name: SECRET_ZONE_HOME_ELEVATION
              value: "${SECRET_HOME_ELEVATION}"
            - name: SECRET_ZONE_HOME_LATITUDE
              value: "${SECRET_HOME_LATITUDE}"
            - name: SECRET_ZONE_HOME_LONGITUDE
              value: "${SECRET_HOME_LONGITUDE}"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
            securityContext:
              privileged: true
    service:
      app:
        controller: *app
        type: LoadBalancer
        loadBalancerIP: ${HOME_ASSISTANT_LB_IP}
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8123
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "home.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
        globalMounts:
          - path: /config
