---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: homeassistant/home-assistant
              tag: 2024.3.3
            env:
            - name: TZ
              value: ${TIMEZONE}
            - name: SECRET_EXTERNAL_URL
              value: https://home.${SECRET_DOMAIN}
            - name: SECRET_TRUSTED_PROXIES_1
              value: ${CLUSTER_CIDR}
            - name: SECRET_TRUSTED_PROXIES_2
              value: ${NODE_CIDR}

            # Home-Assistant Zones
            - name: SECRET_ZONE_HOME_HOUSE_NUMBER
              value: "${SECRET_HOUSE_NUMBER}"
            - name: SECRET_ZONE_HOME_POSTAL_CODE
              value: "${SECRET_POSTAL_CODE}"
            - name: SECRET_ZONE_HOME_ELEVATION
              value: "${SECRET_HOME_ELEVATION}"
            - name: SECRET_ZONE_HOME_LATITUDE
              value: "${SECRET_HOME_LATITUDE}"
            - name: SECRET_ZONE_HOME_LONGITUDE
              value: "${SECRET_HOME_LONGITUDE}"
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 400Mi
              limits:
                memory: 700Mi
          codeserver:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.22.1
            env:
              TZ: ${TIMEZONE}
            args:
              - "/config"
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        nameOverride: *app
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${HOME_ASSISTANT_LB_IP}
        ports:
          http:
            port: 8123
      codeserver:
        controller: *app
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 8080
    ingress:
      app:
        className: internal
        hosts:
          - host: &host home.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
      codeserver:
        className: internal
        hosts:
          - host: &host home-code.${SECRET_DOMAIN}
            paths:
            - path: /
              service:
                identifier: codeserver
                port: http
        tls:
          - hosts: [*host]
    persistence:
      config:
        existingClaim: home-assistant-config
