---
blocking:
  blackLists:
    ads:
    - https://big.oisd.nl/domainswild
    - https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/master/Regular%20Hosts.txt
  whiteLists:
    ads:
    - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
    - https://raw.githubusercontent.com/haraldkoch/safelists/main/adlist.txt
  clientGroupsBlock:
    default:
    - ads

caching:
  minTime: 15m
  prefetching: true
  prefetchExpires: 2h

conditional:
  mapping:
    ${SECRET_DOMAIN}: tcp+udp:${K8S_GATEWAY_IP}

log:
  level: info

ports:
  dns: 53
  http: 4000

prometheus:
  enable: true
  path: /metrics

upstreams:
  groups:
    default:
      - 1.1.1.3
      - 1.0.0.3
