---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: nodo-rflink-device
spec:
  rules:
    - # Nodo-Shop RFlink SOMFY
      name: nodo.rflink
      labels:
        nodo.feature.node.kubernetes.io/rflink: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            class: { op: In, value: ["02"] }
            vendor: { op: In, value: ["2341"] }
            device: { op: In, value: ["0042"] }
