apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:/8V80UTUVI24mAOB0/AIbMxFNLWiudk4URAWgkdfaXOqGUVj,iv:0VWaebigReR7RIEYBwzt6UJNriRHYnU6wk37LTOZXb4=,tag:ow0bDhQCkIgDSPZvBCRhqg==,type:str]
    TUNNEL_TOKEN: ENC[AES256_GCM,data:2ws6YK+2qikH7Ocdi8BUON976AzUo9eyCHmNg6Ce2itsI2CQQvcu7w==,iv:2aSASQElRyXar4WjbSOEB1BR7f04KE9drm4wc5xUjdw=,tag:mcgcOVjc2bHEQcpKFzHq8A==,type:str]
    credentials.json: ENC[AES256_GCM,data:fII9J9AXmrfM67rZlFdIP873vrpNeyZBjMRKlUl4SAoddPCzRKalLyYgw2e/vewaS6KsokkP1BUkszFcn03iBpuCafwrp3JZ5LXrNRxOxrUffDjmm7kdC6nhte4+Wf1DREyaJopeyhU05rGg1YNd+KA9Je1LUVpLhLXR69dXPwlSB/yuofRbNKtDF1CWz7ILhzLOIW6ETo8wl7ku2HglspHhjAPdwyqMac1tIy1swg==,iv:7Sf5hqJXLONOmNxzCF3rVaBYr52O3TXjuF8VzVVXlxU=,tag:K9+EdKgXotF6AQp4TpugMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qmqm5086l36pa9j6shx87s4ja0ldm0mh389j9hqx6fwt8y44laxqhfgn6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBad2lha1UwbVMyS0xsYXhS
            bU4zU0oyVUVTanBLcVBILzhVNG51WFY4RjE4CnpWQTNmSUxoZGpVWkhhSzVYMXZS
            K0xBRmtsTEdMblUrdzc2a1pwd0xYL3cKLS0tIHZyeTExbDFmaGZIY2thZXhvY1hF
            SmR1c1pja2k5bVdoNWtid292Uzc2eWcKVwEsWLYBkQGcH3CuookteRMWAbNv96SH
            JLvjDdhfYd+BCCs6hAT6O76kB6J68XNznwlrnEmSryZ48faDQ8CyPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-26T00:15:20Z"
    mac: ENC[AES256_GCM,data:rxdcK3DOfrQhUmjffjdShnLnPy/42YkWUQIYwFz3QX21ZUuCtR3rvx+LMxz5BL+IkykgxFm/3TMFzF9MzFDtmB+CBxwQSU5E+31Haw1YkQxYRecF41iLzuUl0ZbixpEPapZgO0GvEEicwpfy/98LJfmifzwbE/KuNfqU8EXM2VU=,iv:VxcraRo8Cu0/ziDF3Whmm8tbhXtFgvW2PZ5PrSZJyyU=,tag:KMGPD9bLcGhWjJxx4yMNqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
