apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Ds6bLMy+kOls810hxIztyt365Z3FHHBMmzbpXEJYbB5WDXco,iv:UvFBCIqphaZbXvRrcc+FgpEVusv4WxddrE6CIF1WDd4=,tag:pu9nqJqK6v73aeyYy/btPQ==,type:str]
    TUNNEL_TOKEN: ""
    credentials.json: ENC[AES256_GCM,data:y6pLa9U4Mje7JWWkRuMNB6+QwUmNepHmLSDM4+1PUzjqqmoFgq99vbYbPcZFam+ao4/Yr8koRJXxKbgtcer2vFOvWya/5I+epOc83NOekXqpYU3sWnEvVEKUYijFXuN1gvYWRsJO47L9vwqCU93mIijBzCr6iEdrd5jOMxDL+6IxBucNAubmuygqOQ5NXyCPcGR5dIn8ndRRhUxNJYlxRF1cx6wWUO3iBabi4woyFQ==,iv:tKHuy4LP/a+C4FOZL49pySx4DgHdws8Vw15TWN+v6Go=,tag:8x2npuFQipf6KBaCRQd7Pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qmqm5086l36pa9j6shx87s4ja0ldm0mh389j9hqx6fwt8y44laxqhfgn6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QXNyWXlyWUVieWVGbEZX
            UldZSDJHZ3c2WVIvZ2NGQ0QvZ2J3cC9mTkJFCk16YjBaWXJ6ek5IelJSa2M3YmI1
            TnQ1aEZMdmFuczVyaUN4ai9PR1FwZmMKLS0tIFVXN2JvTHFCUXNQNDIzM21pVjds
            dkJvaFZML2E5Z1lNdWlReFN1SXV0d0kK7uju2YS/5yi41saYYZDHp7ZMhdtXNLQM
            37qBo1EizjWuU/rz92Z/OWlgCavAWo0NXFoOpVuXx40DNMM2BYH0PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-30T13:35:57Z"
    mac: ENC[AES256_GCM,data:Sks6YuBNjg0RM2m2ZGhYDYuZ+NHZxugo9LDu+822xzCRZZzVEtr40pG+lGydRpARDvntoF60CGJ0wkNYaHhMZ+GvIg0FbQ8WqALjHj10476Mh3p1oXKqEbNw2VKXgVGP+rldQoAiJfQKMBrjjEIFVr/Zpi/VL1sOgusS0ax9dNM=,iv:hx8w7RDBnaccOkrk51sXzAl4n1lLqf+TXaBhvVj4p2I=,tag:DBxDKG9NxltlkVuUfKvPsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
