---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: photoprism-database
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb-galera
      version: 13.0.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    replicaCount: 3
    db:
      name: photoprism
      user: photoprism
      password: ${SECRET_PHOTOPRISM_MARIADB_PASSWORD}
    persistence:
      storageClass: openebs-hostpath
