apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:txiMehO4qrZ7S7RI1Ib/Qb0xlaqGS8H/8LgQKWpZbt4lks2YR7iYHQ==,iv:bTqNOutFTRALI528/fDBF4qsa1WhAWeRkIVM6OWWjdg=,tag:5id4DdmLDulJph/wJl1w9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qmqm5086l36pa9j6shx87s4ja0ldm0mh389j9hqx6fwt8y44laxqhfgn6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQ25DNWU1YkhCV3JLa0ZW
            VzJLZ0xueFdGWEJkVmEvS1dDZ3l3WGFpOVRRClRvOWE3NVJWQ3BiZnpPZCtBdkVE
            NlZpRHVyYlJsTEVncVZzajNkY2g1OGsKLS0tICtQOXJ3M1FDQ1N3ODA5UzcxVldO
            MGN0U2JycUpTYXViSU5Hcmt3VEZLVXcKr2pByOFcBaCqMnCHbgP4mf7gJkSi3UsY
            Ymbbj/DBxBsjo6TMC6yRMG4vU81EDYff3y1+Sj2PhXwxHa1jzAGHAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-23T20:26:56Z"
    mac: ENC[AES256_GCM,data:XmbbErc1XaP6gBupA37B+Hpz3HuFsAWo/h9JWLnd2yOb0bkHzFjhkKj7w7bghmwgacZa5RtmZBXbihK4lTi3ZKQF7y5NkCpt7a8diuockmCPWJnRQq7qqPNh015kZBzjUjfq/8+Y9itB5Gof9tsLWT/w5UCtopLmZVE+CNJ9qpA=,iv:6IJWVNwRVqjF3mg8wkUu5m8nXh4JEe0Kln3Ml0311ms=,tag:awkiw9lfGgA/F+n1Yn0kWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
