apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:hE85x2Sr+JjPddGIcr63sRfRrik4y/P5SJ0+dOsmGgMBtghK7kQDtA==,iv:sCY4I9pgp+4294tDVz76PCyLwsoDhOw12YJbbYqnByI=,tag:XOViAs7L8zfqoXrYoDUIvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qmqm5086l36pa9j6shx87s4ja0ldm0mh389j9hqx6fwt8y44laxqhfgn6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWR2pMamdhOEFPbUJCYWdE
            cHlFRzdBSk02dzF0OU9Kd0pmVFRhaTVwTzBzCm01YUNITGcvNFQrcWMvNzNYaGhn
            M1ZOQzQxTDFzRHhtaEVRNlRlWmswS3MKLS0tIHhiejlWYjFsdERURGhORmc3endG
            N0VkRVJ3WUJENHo0UFIwbVpnZkV4RUEKANu5kqMgjTLzRb4uNZlntFZQNtIc9a8a
            hOfD5as5kAgHDcokj3Ro75IpsPxBkvahf2YwWbYAJhtLuoVd5AMMsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-29T00:38:31Z"
    mac: ENC[AES256_GCM,data:gltdRsmaWhn926H8fGdZtnQKUc3hW8kAyRqq6bAsAnV79earqqb5FBDE9KCOtJu2sg4vn7p5OnDnZmvrSdocCW1yc59lY9UqwDWzs6ssTFOPOFep3L9TDqz0YdyJVqJNcE031tyw79sJpJJXR8zKoNFpOaQonNGCMiGvvYRzwKE=,iv:yJKEuFijp+zfx/PnqN7msyLE/YfdaaTP0bBjCRThbxY=,tag:nKXvKPMSYrDL/Pi+yqyP8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
