---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app immich-database
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/media/immich/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: immich-postgres-rw
      namespace: media
    - apiVersion: v1
      kind: Secret
      name: immich-postgres-app
      namespace: media
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: immich-postgres-1
      namespace: media
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: immich-postgres-2
      namespace: media
    - apiVersion: v1
      kind: Pod
      # NOTE: this needs to stay in sync w/ the number of instances in the keycloak cluster.
      name: immich-postgres-3
      namespace: media
  dependsOn:
    - name: cloudnative-pg
---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app immich
#   namespace: flux-system
# spec:
#   targetNamespace: media
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   path: ./kubernetes/apps/media/immich/app
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-kubernetes
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
#   dependsOn:
#     - name: nfs-subdir-external-provisioner
#     - name: immich-database
