---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app blocky
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      blocky:
        replicas: 2
        strategy: RollingUpdate
        annotations:
          configmap.reloader.stakater.com/reload: &config blocky-config
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/0xerr0r/blocky
              tag: v0.23
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 53
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 512Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                add:
                  - NET_BIND_SERVICE
                drop:
                  - ALL
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    ingress:
      app:
        className: internal
        annotations:
          hajimari.io/enable: "false"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: configMap
        name: *config
        globalMounts:
          - path: /app/config.yml
            subPath: config.yml
            readOnly: true
    service:
      app:
        controller: *app
        nameOverride: *app
        ports:
          http:
            port: 4000
      dns:
        controller: *app
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${BLOCKY_LB_IP}
          external-dns.alpha.kubernetes.io/hostname: dns.${SECRET_DOMAIN}
        ports:
          dns-tcp:
            enabled: true
            port: *port
            protocol: TCP
          dns-udp:
            enabled: true
            port: *port
            protocol: UDP
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
