apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: keycloak
spec:
  instances: 3
  storage:
    size: 50Gi
    storageClass: openebs-hostpath
  bootstrap:
    initdb:
      database: imich
      owner: imich
  monitoring:
    enablePodMonitor: true
