apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: media
spec:
  instances: 3
  storage:
    size: 100Gi
    storageClass: openebs-hostpath
  bootstrap:
    initdb:
      database: imich
      owner: imich
      postInitTemplateSQL:
        - "CREATE EXTENSION IF NOT EXISTS vector;"
  monitoring:
    enablePodMonitor: true
