apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: media
spec:
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3-v0.3.0
  instances: 3
  storage:
    size: 100Gi
    storageClass: openebs-hostpath
  bootstrap:
    initdb:
      database: immich
      owner: immich
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
    shared_preload_libraries:
      - "vectors.so"
  monitoring:
    enablePodMonitor: true
