apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: media
spec:
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3-v0.3.0
  instances: 3
  # primaryUpdateStrategy: unsupervised
  storage:
    size: 100Gi
    storageClass: openebs-hostpath
  bootstrap:
    initdb:
      database: imich
      owner: imich
  monitoring:
    enablePodMonitor: true
