---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave-js-ui-config
  namespace: home
  annotations:
      nfs.io/storage-path: "zwave-js-ui-config"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-subdir
  resources:
    requests:
      storage: 1Gi
