apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:Edl33O0zqRaRMdanu8LO7k9YfkxgT9fNFF/VyXdTyHNqw8VwuWnOfGn3CyRkosgDsxUnJlzx69bL5pdjO2o3MffCoc56CVSFbcexfPFZkpat8iAVNe3syAnNMTdlKg==,iv:nSRGmz/wj+y8KvdPFFiMs80LkyL+16Lm1HyHxcy2EFk=,tag:2n8UaZkO3LiKebbgfi7+Mw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:brjL0o5K5X6CHYI=,iv:0EJ7YQ5dyiMMUnE3bL21ylTnhKGr57icQLgTKE/KISA=,tag:mcY2lywXpupWUcj5qK7xvg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:8fn//jJUvCGzaxujqpM=,iv:4dsd9DZBuhXvl0PVJfDixZzPFxvIOhpjvXuPgJOowPY=,tag:E/PAWgNzysP5WpHUgOjdlg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:mclhHXajxpc65lweCJ/94FMDJaH/psBuJ/mMrrpjLCPKPXFX,iv:2KJlRAprYXmA5gYqw00UgO3VCKJhsZ2T3k6l1TuWPxU=,tag:pZd4fYuvih45+DshgAkB9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qmqm5086l36pa9j6shx87s4ja0ldm0mh389j9hqx6fwt8y44laxqhfgn6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuT2oxODZCeUwycXNNTGw4
            MHZvQXdNT3ZIOVJlaG5FamhRcnVuNEYwOHhZClQrNmt0OTZnQjBEd1UvK0grTnJ5
            SHdpTENwTEdTMG1YbVBXNEFLNWNUWmsKLS0tIHY5RkF1dStoMnhPekU4R21wQ0s4
            TEQzS3dNSG5pdXFuTjFGOGdkVkd2MjQKgsUKr4jhzQUEtRdZJ/kqgt0j2Irvtdx6
            2SsU7rKULfFCozP7fRj/gwgyaXEV+7B5SmTlj/u6Zh3szdgxiNmD+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-26T00:15:20Z"
    mac: ENC[AES256_GCM,data:UdTMDnuWgGrJdDvGBQT6VidpZXVAXuwq4PycsFhF+IA1ffHhp7w3DSR1PhXhwtZ3ZfK1neeJD/u+Qes30DUWX1wPPgMDggre8BCxg5opDAEHITXOWWSWK9FaSXAbHGjnU40kBUk+NE7NrqwhjlsbJfLjsnyTD9kYU1N28Tfc8+A=,iv:V1vZnCG5l5pYAaowQhvWyd8ayAI2U2oMqbdIihIpZNU=,tag:wUvUN0crZId4eCIUu9mt6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
