---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: photoprism
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      photoprism:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/photoprism/photoprism
              tag: 231128
            env:
              ## See other config options from PhotoPrism documentation: https://docs.photoprism.org/getting-started/config-options/
              TZ: ${TIMEZONE}
              PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}
              PHOTOPRISM_SITE_URL: "https://photos.${SECRET_DOMAIN}/"
              PHOTOPRISM_SITE_TITLE: "Green's Photos"
              PHOTOPRISM_SITE_AUTHOR: "Rusty Green"
              PHOTOPRISM_APP_NAME: Photos
              PHOTOPRISM_ORIGINALS_LIMIT: 4000 # in MB (default 1000)
              PHOTOPRISM_STORAGE_PATH: /photoprism/storage
              PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
              PHOTOPRISM_IMPORT_PATH: /photoprism/import
              # Database
              PHOTOPRISM_DATABASE_DRIVER: mysql
              PHOTOPRISM_DATABASE_SERVER: "mariadb-mariadb-galera.photoprism.svc:3306"
              PHOTOPRISM_DATABASE_PASSWORD: "${SECRET_PHOTOPRISM_MARIADB_PASSWORD}"
            resources:
              requests:
                cpu: 250m
                memory: 500Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/status
                    port: &port 2342
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: &host "photos.${SECRET_DOMAIN}"
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        mountPath: /photoprism/storage
        existingClaim: photoprism-config

      originals:
        enabled: true
        mountPath: /photoprism/originals
        existingClaim: photoprism-photos

      unsorted:
        enabled: true
        mountPath: /photoprism/import
        existingClaim: photoprism-photos-import
