---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
spec:
  interval: 30m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.18
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    nfs:
      # Example: /volume1/storage
      path: "/volume1/storage/homelab-production"
      # Example: 192.168.1.49
      server: "192.168.1.49"
    storageClass:
      defaultClass: false
      name: nfs-subdir
      # Example: "${.PVC.namespace}-${.PVC.name}" or "${.PVC.namespace}/${.PVC.annotations.nfs.io/storage-path}"
      # pathPattern: ${NFS_SUBDIR_EXTERNAL_PROVISIONER_PATH:=${.PVC.namespace}-${.PVC.name}}
      pathPattern: "${.PVC.annotations.nfs.io/storage-path}"
      reclaimPolicy: Retain
