apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:SUjZDlAvz1xZdXjdj14V6UigInOoy2+p0ur1YcOor1o=,iv:Ayr1i9NzP0J7G4apf6DCNcmhbgG234Jaqwh5Cb21l6w=,tag:2kddmoon5r8CJ2/GFAmNnw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qmqm5086l36pa9j6shx87s4ja0ldm0mh389j9hqx6fwt8y44laxqhfgn6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdWQwai83cldTVnlFVnFs
            SHROUTZnaGhDUHp1WjRadGs1RWxpUjM5ajNNCjlLS2MzZ2NIWVhjeUZqTWNydnA3
            bWhaZExYaUlvQ1E0Uncxdk9vSUpGV2MKLS0tIGViR3VHTFIrc0twMjNSS1hCTGJK
            UFIreHd6VUE5ejN1eFVubmxzY21CVkkKiW4P2pda22SBzinU11hjzAXc2q7tL7y9
            7Lk6T8HGIr5uzoz/iZxgqFglXjkPEos/+t+SC9L9lVd/z8XbqNBJrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-29T21:06:58Z"
    mac: ENC[AES256_GCM,data:z8ksholtc1tkmVM+yHIQajiqnFLoNWjtrX5VPWL0yRvqkzhOzw8fV6IktwWlpftL9/d0+EjW1uQ8b3tk0GPvJGBV+Tb8k+e5llIFR9pdZ1YAcO1zcaKMN0enICmfKQMtaclvuvjGRQ45k6Uk/+3VbOtIpokn5mJjBXC3wd6h7No=,iv:phzKwh0KKRaIAzgoR2vYUUulaUNRn7NBxGU3gljh9wU=,tag:1ON/g46fD+zLcOCi2w9CLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
