apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:RNlK/mYRkzWgACsy2XayYxeVMzwunWQw+rUtRztKO4Y=,iv:qmScdbi8r+mJT9WLU2ewyoF9olA+byg8qf2bK2k10Ms=,tag:OW/kyQUuz2dbZ0YH+UvbeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qmqm5086l36pa9j6shx87s4ja0ldm0mh389j9hqx6fwt8y44laxqhfgn6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArd1BydEp3WUpicitxRVQ2
            UFNqem0xbG9ZWnNzOUVDdTkvWnBMVnNaWVZzCkI1SFl4bzFQUWlIZGxRWllQNUJq
            UGROOXRWWE1na1c1UGdnZ2k1TG4xdVkKLS0tIEhwZjRpOU4zZUMycWg0TjVDUWE2
            RDBxbVF5eTlzd2xsbDc0OXNLOXAvbXcKfF/+Y2gUWoHTRtJm/hn+BY+8VjBMnRjX
            TajRro422sxTBnEPRjuUl/2FbSSSQXaucUeASmlvVBoMTP+umlxNvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-29T02:01:50Z"
    mac: ENC[AES256_GCM,data:iPOtyrPFIepGeB5dwkFU689svjwCfrDkaJK82isdhQeGLmiX2gVYIngbSe2+6nU8TVIQVIHKNkpJijZ6pefRIBMFRYl3/DUWEOVvfsIDcIozL//80Mwyp8w5yAPZLAhbApUpFuQYIvhpWlpmZ9egyemS8OA7g1U68w1kzI8SNPA=,iv:8BTuVhXIFtxKbqcF1b42of0xUrx29vaqHYYchd88/wM=,tag:3GdEk0FATBuClAsPMd3wng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
