apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:zm0IkgDUWRwtbfW2/nKTZoCx3sj4P+0y+k4WB/U3Hzg7x9P4saIkEw==,iv:ieA+K2zjDLvhKyvs8tqWsG9sIuXO83C+0V7JOdNW3dU=,tag:4AekKMGdcg57Tu5yf/cgDw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qmqm5086l36pa9j6shx87s4ja0ldm0mh389j9hqx6fwt8y44laxqhfgn6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZllqUDA4SWxGNGJQU0wx
            WGNObHRFWmN5K0o4azYzcmN5RzFKN3drUFFnCk9NZFJ1WlJZNU9TTmNIMjgxZ3Y5
            RFIrSS9jcXFySk0wZFZSS0xWdGs3TnMKLS0tIENtUWNHa3c4VWUyUFhnL21iS3A4
            UmNxNjduOS8zTlRSYW1NNDNuNkFTS1EKHbQYQyw5Mg4mb8olszK7sLwX9bsyXOGM
            KFklowUpXBFCsbwHJ2qqZlO/BQ7mbjkQRTknv5WweIv5SyQc+2uenw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-28T21:29:16Z"
    mac: ENC[AES256_GCM,data:iTXCmn6V5wNDs/wCQ+kJFcEkI0V2s19Myn8yt8lDhn4r1wLUrmUcVGfF3fUJDKROT/l16ntW6kfPtQHWeEFRDlxqhqX5H+6Yx8v+sWWYzUZmknkQlHyxBWtd+1ibHnhaeejalNniGU5MU96UqFyttAnq1hwIUyKZZG/L75FGDRc=,iv:2dXEhPNUwDb11OLdTYwQZNgxnAwbEb8QoHENjIfYSvM=,tag:aqfrMQVq0eTLHHaX+psm8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
