apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:sdM+NyQl4XpDuqNOnPzojOZg8QoKE7sNQRrud5ceOEOijVQhUwm7ag==,iv:yyMLttj8FB1gdODjVWbR28U61XhmbZsfLqNwwEQmvRo=,tag:l+kfn8OxFc8fDrSg+PsxOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qmqm5086l36pa9j6shx87s4ja0ldm0mh389j9hqx6fwt8y44laxqhfgn6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwQWROR0taRzN4dGJyUU1C
            ZkVBUmlvU0JsRHBvYjZrUzF0eE5CbGFOTVhnCkc2MlJ6b1VmRHNRNDZUd0RHb0V6
            dzdXUWc4cHduYWg4bFRMQTlFZCtaR1kKLS0tIDJSSXpDWmRrbUNPV2FyeXJINFMw
            TnZYcXVzLzlsZVY5clBaaFI5aTA5K2cK8pvvig3ZfOiZ6deFguHPKYGOX8ZXAElI
            /1k0Q8qxsOBxE1W7R38RnuOo62phjxF27Gesjjx6g8B1PfPprikpDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-30T13:35:57Z"
    mac: ENC[AES256_GCM,data:ggzD25JO3rxKp+FVhCct3t7yNuzL3QdPoH2TVLhfl2ynZLV4yNaC7m0W3qMVJTtTRnycf545ddI5gKCjIlJmCUo0Y20AWyjVVLtiF/iWTTa7Om6SF5sm8JrW9oUIZWmeIB7OpV+epc2xP64oYotWiLo5pocmmIP1xZ9DIVrYkeE=,iv:90ddeSjk2Mr9+yZ8TG2y0CYgKolErtJwPSzkHxgG8ls=,tag:d16Is0vLtsCZOzgwcMUwaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
