---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: emqx
spec:
  interval: 30m
  chart:
    spec:
      chart: emqx
      version: 5.6.0
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      repository: public.ecr.aws/emqx/emqx
    replicaCount: 3
    recreatePods: true
    emqxConfig:
      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_AUTH__MNESIA__PASSWORD_HASH: plain
      EMQX_DASHBOARD__DEFAULT_PASSWORD: ${SECRET_EMQX_ADMIN_PASSWORD}
      EMQX_AUTH__USER__1__USERNAME: ${EMQX_USER}
      EMQX_AUTH__USER__1__PASSWORD: ${SECRET_EMQX_PASSWORD}
    service:
      type: LoadBalancer
      loadBalancerIP: ${EMQX_IP}
      externalTrafficPolicy: Local
    ingress:
      dashboard:
        enabled: true
        ingressClassName: internal
        annotations:
          hajimari.io/appName: "EMQX"
          hajimari.io/icon: simple-icons:eclipsemosquitto
          nginx.ingress.kubernetes.io/custom-http-errors: "418"
        path: /
        pathType: Prefix
        hosts:
          - emqx.${SECRET_DOMAIN}
        tls:
          - hosts:
              - emqx.${SECRET_DOMAIN}
      mqtt:
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/custom-http-errors: "418"
        path: /
        pathType: Prefix
        hosts:
          - mqtt.${SECRET_DOMAIN}
        tls:
          - hosts:
              - mqtt.${SECRET_DOMAIN}
    metrics:
      enabled: false
    persistence:
      enabled: true
      existingClaim: emqx
    resources:
      requests:
        cpu: 100m
        memory: 150Mi
      limits:
        memory: 512Mi
